### ISSUE TITLE
Some Suggestion On Future Improvements

### ISSUE THREAD

**Issue by markzhengma** [brizmon/project2#1]
I love the project. Nice and clear and with really cool styles. It grabs fonts from google fonts api and saves onto personal account. It could be downloaded as well.

For the improvements, I would say, besides fixing the saving issue, trying to add tabs to the fonts might be a good idea. It would ease the process of searching new fonts and more tags would make the filter function more powerful!

**Comment by brizmon** [comment]
I agree with your suggestions, I'll take them into account. Thanks!
